default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: localhost
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  <<: *default
  database: ucalendar_production

development:
  <<: *default
  database: ucalendar_development

test:
  <<: *default
  database: ucalendar_test
