inherit_from: ../.rubocop.yml

Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false